name = "multiplayer-career-limiting-maneuver"
main = "src/server/index.ts"
compatibility_date = "2025-04-01"
upload_source_maps = true

[assets]
directory = "public"

[build]
command = "npx esbuild src/client/index.tsx --bundle --outdir=public/dist --splitting --sourcemap --format=esm"

[durable_objects]
bindings = [
  { name = "Globe", class_name = "Globe" }
]

[observability]
enabled = true

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Globe"]
